SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 330
PLAYER_SPEED = 220
PLAYER_SHOT_SPEED = 550
PLAYER_SHOOT_COOLDOWN = 0.27
BASE_SCORE = 10

SHOT_RADIUS = 5

LIFE_ICON_START = 25
LIFE_ICON_SPACING = 30
